import { Plus_Jakarta_Sans, Inter } from "next/font/google";
import "./globals.css";
import { LeftSidebar,Topbar,Bottombar } from "./components";
import Provider from "./provider";
const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"],   variable: '--font-jakarta',});
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Geegpay",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en">
      <Provider>
      <body className={`${jakarta.className} bg-[#fafafa]`}>
      <Topbar />
        <main className="flex flex-row">
          <LeftSidebar />
          <section className="main-container">
            <div className="w-full">
              {" "}
              {children}
            </div>
          </section>
        </main>
        <Bottombar />
      </body>
      </Provider>
    </html>
  );
}
